---
title: "Code for all problems"
author: "Sho Kawano"
date: "2024-07-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


##Problem 2

```{r}
set.seed(7)
data <- read.csv("data/538_wnba/simplified_data.csv") 
data %>% sample_n(10) %>% 
  select(player_ID, Player, year=year_ID, Age, Team=Tm, Games=G, Position=Pos, Minutes=MP, True_Shooting_Pct=TS_pct) 
```


##Problem 3

```{r}
days <- 1:7
salmon <- c(7, 8, 19, 9, 11, 10, 16)

par(mfrow = c(1,1), mar=c(5, 3, 3, 3))
hist(salmon, xlab="Number of Salmon caught", main="Distribution of salmon caught over 7 days", ylab="Count", col="lightblue") 
```

```{r}
sum(salmon)
mean(salmon)
```



##Problem 5


```{r}
data <- read.csv("data/538_wnba/simplified_data.csv") 
plt <- data %>% ggplot(aes(x=TS_pct)) + 
  geom_histogram(bins=20, color="blue", fill="lightblue") + theme_bw() +
  labs(title="Distribution of True Shooting Percentage by WNBA players", 
       subtitle = "1997-2019 Seasons") + 
  xlab("True Shooting Percentage") 
plt
```


##Problem 6


```{r}
histplt <- iris %>% ggplot(aes(x=Petal.Length)) + 
   geom_histogram(bins=20, color="blue", fill="lightblue") + 
   theme_bw() +
   labs(title="Petal Length of Iris Flowers") + 
   xlab("Petal Length") 
 
boxplt <- iris %>% ggplot(aes(x=Petal.Length)) + 
   geom_boxplot(color="blue", fill="lightblue", alpha=0.3, ymax=0.1, ymin=-0.1) + 
   theme_bw() +
   theme(axis.text.y=element_blank())+
   xlab("Petal Length") 
 
histplt + boxplt
```


```{r}
boxplt <- iris %>% ggplot(aes(x=Petal.Length, y=Species, fill=Species, colour = Species)) + 
   geom_boxplot(alpha=0.5) + 
   theme_bw() +
   xlab("Petal Length") 
boxplt
```

##Problem 7

```{r}
flu <- c(6, 8, 25, 11, 5, 9, 6)
sum(flu)
mean(flu)
median(flu)
```

```{r}
boxplot(flu)
```


```{r}
flu <- c(6, 8, 25)
sum(flu)
mean(flu)
median(flu)
```




##Problem 8


```{r }
library(taylor)
duration = taylor_all_songs$duration_ms / 60000 # in minutes
duration = duration[!is.na(duration)]

par(mfrow = c(1,1), mar=c(5, 5, 3, 3))
hist(duration, main="Duration of all Taylor Swift Songs", 
     xlab="Song Duration in Minutes", ylab="Count", col="lightblue")
```


```{r}
par(mfrow = c(1,1), mar=c(5, 5, 3, 3))
hist(duration, main="Duration of all Taylor Swift Songs", xlab="Song Duration in Minutes", ylab="Count", col="lightblue")
abline(v=quantile(duration, 0.1), lty=2, lw=2, col="blue")
# abline(v=quantile(duration, 0.5), lty=2, lw=2, col="blue")
abline(v=quantile(duration, 0.95), lty=2, lw=2, col="blue")
```


##Problem 9

```{r}
data("storms")
storms %>% head()
```


```{r}
by_storms = storms %>% group_by(name, year) %>% summarise(wind=max(wind)) 
```



```{r}
windspeed = by_storms$wind
par(mfrow = c(1,1), mar=c(5, 5, 3, 3))
hist(windspeed, main="Max Windspeed for all Atlantic storms", 
     xlab="Maximum Observed Windspeed (knots)", ylab="Count", col="lightblue")
```

```{r}
summary(windspeed)
```

```{r}
mode0 <- function(x) {
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}

mode0(windspeed)
```


```{r}
sd(windspeed)
IQR(windspeed)
max(windspeed) - min(windspeed)
```


## Problem 10

```{r}
load("data/census_data_CA.RDA")
all_data = all_data %>% 
    # filter(rentBurden>0.2) %>% 
  mutate(geo_name=gsub("County, California", "", geo_name)) 
```


<!-- ```{r} -->
<!-- all_data %>%  -->
<!--   ggplot(aes(x=income, y=no_car)) + geom_point() +  -->
<!--   geom_label(aes(x=100000,y=no_car-0.02, label=geo_name), data=all_data %>% filter(no_car>0.2)) + -->
<!--   geom_smooth(method = "lm", se=FALSE)  -->
<!-- ``` -->


```{r fig.dim=c(10, 5)}
library(patchwork)
plt1 = all_data %>% 
  ggplot(aes(x=female_only, y=povPerc)) + geom_point() + 
  geom_smooth(method = "lm", se=FALSE) +
  xlab("Rate of single mother households") + 
  ylab("Poverty rate") 

plt2 = all_data %>% 
  ggplot(aes(x=degree, y=povPerc)) + geom_point() + 
  geom_smooth(method = "lm", se=FALSE) +
  xlab("Rate of households with college degrees") + 
  ylab("Poverty rate") 


plt1 + plt2 
```



```{r fig.dim=c(10, 5)}
library(patchwork)

plt2 = all_data %>% 
  filter(pop > 50000) %>% 
  ggplot(aes(x=degree, y=povPerc)) + geom_point() + 
  geom_smooth(method = "lm", se=FALSE) +
  xlab("Rate of households with college degrees") + 
  ylab("Poverty rate") 

plt4 = all_data %>% 
  filter(pop > 50000) %>% 
  ggplot(aes(x=degree, y=rentBurden)) + geom_point() + 
  geom_smooth(method = "lm", se=FALSE) +
  xlab("Rate of households with college degrees") + 
  ylab("Rent burden")  


plt2 + plt4
```

```{r}
all_data = all_data %>% mutate(population=pop/10^6)

plt2 = all_data %>% 
  filter(pop > 50000) %>%  
  ggplot(aes(x=degree, y=povPerc)) + geom_point(aes(size=population), alpha=0.5) + 
  geom_smooth(method = "lm", se=FALSE) +
  xlab("Rate of households with college degrees") + 
  ylab("Poverty rate")  +
  labs(size="Population (in Millions)")

plt4 = all_data %>% 
  filter(pop > 50000) %>% 
  ggplot(aes(x=degree, y=rentBurden)) + geom_point(aes(size=population), alpha=0.5) + 
  geom_smooth(method = "lm", se=FALSE) +
  xlab("Rate of households with college degrees") + 
  ylab("Rent burden")  +
  labs(size="Population (in Millions)")

ggpubr::ggarrange(plt2, plt4, common.legend = TRUE)
```


```{r}
all_data %>% 
  filter(pop > 50000) %>% 
  ggplot(aes(x=degree, y=rentBurden)) + geom_point(aes(size=population), alpha=0.5) + 
  geom_smooth(method="lm", se=FALSE) +
  geom_smooth(se=FALSE, color="darkblue", lty=4) +
  xlab("Rate of households with college degrees") + 
  ylab("Rent burden")  +
  labs(size="Population (in Millions)") + theme(legend.position = "top")

```



```{r}
library(usmap)
plt1 <- plot_usmap("counties", values = "poverty", data=all_data %>% mutate(poverty=povPerc), include="California") + 
  theme(legend.position = "bottom", legend.text = element_text(angle = 45, vjust = 1, hjust=1, size=8),
        legend.title = element_text(size=12))+
    scale_fill_viridis_c()

plt2 <- plot_usmap("counties", values = "A", data=all_data %>% mutate(A=degree), include="California") + 
  theme(legend.position = "bottom", legend.text = element_text(angle = 45, vjust = 1, hjust=1, size=8),
        legend.title = element_text(size=12))+
    scale_fill_viridis_c()

plt3 <- plot_usmap("counties", values = "B", data=all_data %>% mutate(B=female_only), include="California") + 
  theme(legend.position = "bottom", legend.text = element_text(angle = 45, vjust = 1, hjust=1, size=8), 
        legend.title = element_text(size=12))+
    scale_fill_viridis_c()


plt1+plt2+plt3 
```



## Problem 16

```{r}
load("data/census_data_CA.RDA")
all_data = all_data %>% 
    # filter(rentBurden>0.2) %>% 
  mutate(geo_name=gsub("County, California", "", geo_name)) 
```


```{r fig.dim=c(10, 5)}
library(patchwork)
all_data %>%
  ggplot(aes(x=assistance, y=povPerc)) + geom_point() +
  geom_smooth(method = "lm", se=FALSE) +
  xlab("Rate of households receiving CalFresh") +
  ylab("County-Level Poverty rate")
```


```{r}
lm_fit = lm(povPerc~assistance, data=all_data) 
lm_fit %>% summary()
```


```{r}
sqrt(0.6593)
```

## Problem 17

```{r fig.dim=c(10, 5)}
library(patchwork)
all_data %>%
  mutate(predicted = lm_fit$fitted.values) %>% 
  ggplot(aes(x=assistance, y=povPerc)) + 
  geom_point() +
  geom_smooth(method="lm", se=F, linewidth=0.5) + 
  geom_segment(aes(xend =assistance, yend = predicted), color="blue", lty=2) +
  geom_abline(slope=0, lty=2, color="blue")+
  xlab("Rate of households receiving CalFresh") +
  ylab("County-Level Poverty rate")
```



```{r}
all_data %>%
  mutate(predicted = lm_fit$fitted.values) %>% 
  ggplot(aes(x=assistance, y=povPerc)) + 
  geom_point() +
  geom_smooth(method="lm", se=F) + 
  # geom_segment(aes(xend =assistance, yend = predicted), color="blue", lty=2) +
  geom_abline(slope=1, lty=2, color="red", lty=2)+
  geom_abline(slope=1, intercept=0.05, lty=2, color="red", lty=2)+
  xlab("Rate of households receiving CalFresh") +
  ylab("County-Level Poverty rate")
```


## Problem 18


```{r}
data <- read.csv("data/AL_team_statistics.csv") 
data %>% head()
```



```{r}
data %>% 
  # mutate(predicted = lm(scoring~batting, data=data)$fitted.values) %>% 
  ggplot(aes(x=batting, y=scoring)) + 
  geom_point() + geom_smooth(method="lm", se=F) +
  geom_point(color="red", size=4, shape=2, data=data %>% filter(team=="Kansas City"))+
  xlab("Batting Average") + ylab("Average Runs Scored") 
```


```{r}
y = data$scoring
```

```{r}
y.hat = round(lm(scoring~batting, data=data)$fitted.values, 2)
```


```{r}
y-y.hat
```

```{r}
data$team[which(y-y.hat==max(y-y.hat))]
```

```{r}
data$team[which(y-y.hat==min(y-y.hat))]
```

```{r}
lm(scoring~batting, data=data)
```


```{r}
data.frame(data$team, data$batting, y, y.hat, residual=y-y.hat) %>% write.csv("mlb.csv")
```

## Problem 19

```{r}
library(taylor)
taylor_all_songs %>% colnames()
```




```{r}
plt = taylor_all_songs %>% ggplot(aes(x=tempo, y=danceability)) + geom_point(alpha=0.6) +
  xlab("Tempo") + ylab("Danceability") 
plt
```


```{r warning=F}
library(patchwork)
(plt + geom_smooth(se=F) + ggtitle("Trend A")) + 
(plt + geom_smooth(method="lm", se=F) + ggtitle("Trend B"))
```

## Problem 20

```{r}
data <- palmerpenguins::penguins
```


```{r}
data %>% ggplot(aes(x=bill_depth_mm, y=bill_length_mm, color=island, shape=species)) + 
  geom_point(alpha=0.9) + xlab("Bill Depth (mm)") + ylab("Bill Length (mm)") + 
  ggtitle("Bill Characteristics of Penguins") + theme_bw() 
```


## Problem 31

```{r}
pnorm(73, mean=66, sd=3.1)
```

```{r}
pnorm(60, mean=66, sd=3.1)
```


## Problem 32

```{r}
pnorm(100, mean=60, sd=30)
```


```{r fig.width=8, fig.height=6}
par(mfrow=c(2,3), mai = c(0.7, 0.5, 0.5, 0.1))

# mean & sd
m=60
s=30

# (a)
curve(dnorm(x,m,s), xlim=c(-3*s+m,3*s+m), ylab="Density", main="A", xlab="Income", xaxt = "n")
 
# define shaded region
from.z <- -3*s+m
to.z <- 2*s+m
 
S.x  <- c(from.z, seq(from.z, to.z, 1), to.z)
S.y  <- c(0, dnorm(seq(from.z, to.z, 1), m, s), 0)
polygon(S.x,S.y, col="blue")
axis(1, at = c(-2*s+m, -1*s+m, m, 1*s+m,  2*s+m))
# (b)
curve(dnorm(x,m,s), xlim=c(-3*s+m,3*s+m), ylab="Density", main="B", xlab="Income", xaxt = "n")
 
# define shaded region
from.z <- 1*s+m
to.z <- 2*s+m
 
S.x  <- c(from.z, seq(from.z, to.z, 1), to.z)
S.y  <- c(0, dnorm(seq(from.z, to.z, 1), m, s), 0)
polygon(S.x,S.y, col="blue")
axis(1, at = c(-2*s+m, -1*s+m, m, 1*s+m,  2*s+m))

# (c)
curve(dnorm(x,m,s), xlim=c(-3*s+m,3*s+m), ylab="Density", main="C", xlab="Income", xaxt = "n")
 
# define shaded region
from.z <- -1*s+m
to.z <- 1*s+m
 
S.x  <- c(from.z, seq(from.z, to.z, 1), to.z)
S.y  <- c(0, dnorm(seq(from.z, to.z, 1), m, s), 0)
polygon(S.x,S.y, col="blue")
axis(1, at = c(-2*s+m, -1*s+m, m, 1*s+m,  2*s+m))
# (d)
curve(dnorm(x,m,s), xlim=c(-3*s+m,3*s+m), ylab="Density", main="D", xlab="Income", xaxt = "n")
 
# define shaded region
from.z <- -1*s+m
to.z <- 3*s+m
 
S.x  <- c(from.z, seq(from.z, to.z, 1), to.z)
S.y  <- c(0, dnorm(seq(from.z, to.z, 1), m, s), 0)
polygon(S.x,S.y, col="blue")
axis(1, at = c(-2*s+m, -1*s+m, m, 1*s+m,  2*s+m))
# (E)
curve(dnorm(x,m,s), xlim=c(-3*s+m,3*s+m), ylab="Density", main="E", xlab="Income" , xaxt = "n")
 
# define shaded region
from.z <- 0*s+m
to.z <- 2*s+m
 
S.x  <- c(from.z, seq(from.z, to.z, 1), to.z)
S.y  <- c(0, dnorm(seq(from.z, to.z, 1), m, s), 0)
polygon(S.x,S.y, col="blue")
axis(1, at = c(-2*s+m, -1*s+m, m, 1*s+m,  2*s+m))

# (f)
curve(dnorm(x,m,s), xlim=c(-3*s+m,3*s+m), 
      ylab="Density", main="F", xlab="Income", xaxt = "n")
 
# define shaded region
from.z <- 2*s+m
to.z <- 3*s+m
 
S.x  <- c(from.z, seq(from.z, to.z, 1), to.z)
S.y  <- c(0, dnorm(seq(from.z, to.z, 1), m, s), 0)
polygon(S.x,S.y, col="blue")
axis(1, at = c(-2*s+m, -1*s+m, m, 1*s+m,  2*s+m))
```


## Problem 37


```{r fig.width=8, fig.height=6}
par(mfrow=c(1,1), mai = c(1, 0.5, 0.5, 0.1))

# (a)
curve(dnorm(x,0,1), xlim=c(-3,3), ylab="Density", main="", xlab="SD's from the Mean", xaxt="n")
 
# define shaded region
from.z <- -1.96
to.z <- 1.96
 
S.x  <- c(from.z, seq(from.z, to.z, 0.01), to.z)
S.y  <- c(0, dnorm(seq(from.z, to.z, 0.01)), 0)
polygon(S.x,S.y, col="blue")
axis(1, at = c(-1.96, -1, 0, 1,  1.96))
```



## Problem 38

Download ACS Data 

```{r}
library(tidycensus)
rent <- get_acs(geography = "county", variables = c(population="B01003_001", poverty="B17001_002"),
                  year = 2022, state = "CA")
```


```{r}
rent %>% head()
```


Used for table in the problem: 

```{r}
rent %>%  pivot_wider(id_cols =NAME, names_from = variable, values_from=estimate:moe) %>% 
  rename(county=NAME, population=estimate_population, estimate=estimate_rentburden, moe=moe_rentburden) %>% 
  select(-moe_population) %>% 
  mutate(estimate=estimate/100, moe=moe/100, population=population)
```


## Problem 40

```{r}
p0 = 0.5
phat = 0.62
SE0 = sqrt(0.5^2/100)
Z = (phat-p0)/SE0
Z
```


```{r}
Z = (phat-p0)/SE0
Z
```

```{r}
1-pnorm(Z)
```

## Problem 41


```{r}
data <- read.csv("data/538_congress/simplified_data.csv") 
```



```{r}
n <- data %>% filter(congress==117) %>% nrow()

df <- data %>% filter(congress==117) %>% 
  mutate(old=age_years>=65) %>% 
  select(start_date, state_abbrev, bioname, age_years, old) 
```


```{r}
mean(df$age_years)
```

```{r}
phat = mean(df$old)
phat
```

```{r}
p0 = 0.168
SE0 = sqrt((1-p0)*p0/n)
SE0
```

```{r}
Z = (phat-p0)/SE0
Z
```

```{r}
1-pnorm(Z)
```

## Problem 43

```{r}
diff = 0.172 - 0.12
n1 = 292
n2 = 203
pooled = (35+35) / (n1+n2)
pooled
SE = sqrt(pooled*(1-pooled)/n1 + pooled*(1-pooled)/n2)
SE
```

```{r}
Z = diff/round(SE, 3)
Z
```

```{r}
(1-pnorm(Z))*2
```



## Problem 44

```{r}
phat1 = 0.12
phat2 = 0.172
n1 = 292
n2 = 203
SE = sqrt(phat1*(1-phat1)/n1 + phat2*(1-phat2)/n2)
SE
```

```{r}
0.052 + 1.96*SE
0.052 - 1.96*SE
```

## Problem 45

```{r}
51/78
29/78
```

```{r}
diff = (51-29)/78
diff
n1 = 78
n2 = 78
pooled = (29+51) / (n1+n2)
pooled
SE = sqrt(pooled*(1-pooled)/n1 + pooled*(1-pooled)/n2)
SE
```

```{r}
0.282/0.08
```


```{r}
Z = diff/round(SE, 3)
Z = round(Z, 2)
Z
```

```{r}
(1-pnorm(Z))
(1-pnorm(Z))*2
```


